<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/spanner/admin/database/v1/common.proto

namespace Google\Cloud\Spanner\Admin\Database\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Encryption configuration describing key resources in Cloud KMS used to
 * encrypt/decrypt a Cloud Spanner database.
 *
 * Generated from protobuf message <code>google.spanner.admin.database.v1.EncryptionConfig</code>
 */
class EncryptionConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * The resource name of the Cloud KMS key that was used to encrypt and decrypt
     * the database. The form of the kms_key_name is
     * `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys\
     * /<kms_key_name>`.
     * api-linter: core::0122::name-suffix=disabled
     * aip.dev/not-precedent: crypto key identifiers like this are listed as a
     * canonical example of when field names would be ambiguous without the
     * _name suffix and should therefore include it.
     *
     * Generated from protobuf field <code>string kms_key_name = 2 [(.google.api.resource_reference) = {</code>
     */
    private $kms_key_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $kms_key_name
     *           The resource name of the Cloud KMS key that was used to encrypt and decrypt
     *           the database. The form of the kms_key_name is
     *           `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys\
     *           /<kms_key_name>`.
     *           api-linter: core::0122::name-suffix=disabled
     *           aip.dev/not-precedent: crypto key identifiers like this are listed as a
     *           canonical example of when field names would be ambiguous without the
     *           _name suffix and should therefore include it.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Spanner\Admin\Database\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * The resource name of the Cloud KMS key that was used to encrypt and decrypt
     * the database. The form of the kms_key_name is
     * `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys\
     * /<kms_key_name>`.
     * api-linter: core::0122::name-suffix=disabled
     * aip.dev/not-precedent: crypto key identifiers like this are listed as a
     * canonical example of when field names would be ambiguous without the
     * _name suffix and should therefore include it.
     *
     * Generated from protobuf field <code>string kms_key_name = 2 [(.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getKmsKeyName()
    {
        return $this->kms_key_name;
    }

    /**
     * The resource name of the Cloud KMS key that was used to encrypt and decrypt
     * the database. The form of the kms_key_name is
     * `projects/<project>/locations/<location>/keyRings/<key_ring>/cryptoKeys\
     * /<kms_key_name>`.
     * api-linter: core::0122::name-suffix=disabled
     * aip.dev/not-precedent: crypto key identifiers like this are listed as a
     * canonical example of when field names would be ambiguous without the
     * _name suffix and should therefore include it.
     *
     * Generated from protobuf field <code>string kms_key_name = 2 [(.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setKmsKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->kms_key_name = $var;

        return $this;
    }

}

